version: "3.9"

services:

  postgres_main:
    image: postgres:16
    container_name: smartgen_postgres_main
    environment:
      POSTGRES_DB: smartgen_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5433:5432"
    volumes:
      - postgres_main_data:/var/lib/postgresql/data
    restart: unless-stopped

  mysql_test:
    image: mysql:8
    container_name: smartgen_mysql
    command: --mysql-native-password=ON
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: test123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  postgres_test:
    image: postgres:16
    container_name: smartgen_postgres_test
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test123
    ports:
      - "5432:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    restart: unless-stopped

  mongodb_test:
    image: mongo:7
    container_name: smartgen_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  cassandra_test:
    image: cassandra:4
    container_name: smartgen_cassandra
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra
    restart: unless-stopped

  neo4j_test:
    image: neo4j:5
    container_name: smartgen_neo4j
    environment:
      NEO4J_AUTH: neo4j/test1234
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: smartgen_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  postgres:
      image: postgres:16
      container_name: smartgen-postgres
      restart: always
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: 123456
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data



volumes:
  postgres_main_data:
  mysql_data:
  postgres_test_data:
  postgres_data:
  mongo_data:
  cassandra_data:
  neo4j_data:
  redis_data:


  